### ISSUE TITLE
SQLLITE3 Disk I/O Error Running On NFS

### ISSUE THREAD

**Issue by toomanycats** [poldracklab/sdcflows#267]
I'm getting a Disk I/O error when running FmriPrep with the `sdcflows` package installed. 
We run our production pipeline on an NFS v4 file system. This looks a lot like the standard sqlite file lock issue I've been reading about.

**UPDATE:** Getting same error without `sdcflows` installed. You can close the issue, but maybe someone knows something in general. Thank you.

196 GB free
python v3.6
pymssql v2.2.5
sqlalchemy v1.3.24
fmriPrep v21.0.2
BIDS v1.7.0
sdcflows v 1.3.3

Is there a work around in `sdcflows` ? 

```sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: PRAGMA main.table_info("layout_info")]
(Background on this error at: http://sqlalche.me/e/13/e3q8```

**Comment by effigies** [comment]
I would use `--bids-database-dir` to point to a location on a local drive that you have write-access to. Perhaps `/tmp/bids` or similar.

**Comment by toomanycats** [comment]
Just a follow up for others who hit this. This error has nothing to do with `sdcflows`. In my case it does appear that NFS is breaking the SQLITE driver. I could create a DB using the command line client `sqlite3` but the python one always broke.

I tested in `ipython` the idea of using `/tmp`.

    from sqlalchemy.engine import create_engine
    conn = create_engine("sqlite:////tmp/test.db")
    sql = "CREATE TABLE 'test' ('col1' int);"
    conn.execute(sql)

No errors and the db file has data. When performed on an NFS mounted space, I always received the error about Disk I/O.
