### ISSUE TITLE
PEPOLAR with GE-EPI and multiple use images

### ISSUE THREAD

**Issue by jmatthews-rotman** [poldracklab/sdcflows#332]
Please feel free to correct me if this isn't the optimal place for this topic, or if I've missed implemented or in development features in this vein.

There are a number of studies that have used GE-EPI rather than SE-EPI for PEPOLAR-style SDC. Here are a selection (the first actually compares PEPOLAR with both SE-EPI and GE-EPI, and traditional field maps, and gives the nod to GE-EPI):
https://paperpile.com/app/p/83879dc2-40c3-01df-be81-84cce654a5ad
https://paperpile.com/app/p/0485efde-2815-0a7c-b428-0b46e0a3f0d0
https://paperpile.com/app/p/472936f8-cc14-0f73-8ec0-16b12df2665f

Unless I've missed something, I don't believe the BIDS spec or sdcflows currently encompasses such acquisitions or methods, but it seems like a good addition. 

There are a few things that come to mind in implementing this:
-I believe the topup analysis is the same. In theory, GE-EPI could probably be collected in pairs and named as fmap-epi and would work, although I haven't tested this. However...
-While SE-EPI needs to be acquired in pairs, GE-EPI only needs to be acquired in the opposite phase encode direction to your functional run. Volume(s) from the functional run can then be extracted and used as the paired image. I imagine the BIDS spec would cover naming the single additional image, and the extraction of the paired image would be implemented in a processing stage like fmriprep.
-It also struck me that one could use pairs of single-band reference images for this purpose. The improved anatomical contrast should improve the results of topup, although untested. Using CMRR sequences, one would again only need one additional sbref image with the reverse phase encode direction, which could be paired with the "free" sbref image from the functional run. Not sure if/how the BIDS spec would reflect this type of dual use (sbref + fmap-epi). Perhaps the image would be labelled as an sbref, and the phase encode direction (and/or an IntendedFor entry?) would alert processing apps of its potential as an fmap-epi.

**Comment by effigies** [comment]
Hi, sorry we missed this.

> -I believe the topup analysis is the same. In theory, GE-EPI could probably be collected in pairs and named as fmap-epi and would work, although I haven't tested this. However...

This would be worth checking.

> -While SE-EPI needs to be acquired in pairs, GE-EPI only needs to be acquired in the opposite phase encode direction to your functional run. Volume(s) from the functional run can then be extracted and used as the paired image. I imagine the BIDS spec would cover naming the single additional image, and the extraction of the paired image would be implemented in a processing stage like fmriprep.

We allow reverse-echo SE-EPI fieldmaps in exactly this fashion.

> -It also struck me that one could use pairs of single-band reference images for this purpose. The improved anatomical contrast should improve the results of topup, although untested. Using CMRR sequences, one would again only need one additional sbref image with the reverse phase encode direction, which could be paired with the "free" sbref image from the functional run. Not sure if/how the BIDS spec would reflect this type of dual use (sbref + fmap-epi). Perhaps the image would be labelled as an sbref, and the phase encode direction (and/or an IntendedFor entry?) would alert processing apps of its potential as an fmap-epi.

If an sbref is available, we can use that in place of an associated BOLD file. If you want to do something more complicated, you can use `B0FieldSource`/`B0FieldIdentifier` to label what images you want to use to estimate fieldmaps. This could be done with two reverse-encoded sbrefs right now.

----

I don't know much about GE-EPI, so please feel free to test things out. If we need to be able to identify and treat GE-EPI differently from SE-EPI, then it would be a good idea to make sure that this difference can be encoded in BIDS first.

**Comment by jmatthews-rotman** [comment]
Thanks for your reply! 

Since posting this I became aware of the B0FieldSource/B0FieldIdentifier notation you mentioned, which does seem to address all of these use cases, and at least one source describing using it with a single paired GE image the way I described. We are working on acquiring some data to test with, and I will post a new more specific issue if anything doesn't work as implied.
