### ISSUE TITLE
Add --bids-filter-file to sdcflows-find-estimators

### ISSUE THREAD

**Issue by effigies** [poldracklab/sdcflows#344]
### What would you like to see added in this software?

To get a view of the dataset as seen by sdcflows when called from a downstream tool, it would be useful to accept `--bids-filter-file` in addition to `--bids-database-dir`.

### Do you have any interest in helping implement the feature?

Yes

**Comment by oesteban** [comment]
I believe this was fully covered with #408 (both `--bids-filter-file` and `--bids-database-dir`). Please reopen if I got something wrong.
