### ISSUE TITLE
syn preprocessing `epi_reference_wf` does not distinguish between different matrix sizes

### ISSUE THREAD

**Issue by eilidhmacnicol** [poldracklab/sdcflows#352]
### What happened?

I have 1 rs fMRI and 3 task fMRI for a given subject. The rs fMRI has a longer TR (1.5 secs) and more slices (36) than the task (1 sec; 24 slices). Despite whether a task filter is passed to fMRIPrep, `find_estimators` [includes all available bold images as the source images](https://github.com/nipreps/fmriprep/blob/fcd825c30b225941231e1fd4f7d231356a456121/fmriprep/workflows/base.py#L537) because the [task filter is not passed to find_estimators](https://github.com/nipreps/fmriprep/blob/fcd825c30b225941231e1fd4f7d231356a456121/fmriprep/workflows/base.py#L381) (which is admittedly a separate problem, so I can open a relevant issue in fmriprep if this is the case).

However, even if all the bold images were passed, I'd expect `init_syn_preprocessing_wf` to either a) check that all images have the same shape or b) create an EPI reference for each image shape rather than bundling them all together.

The resulting shape is the same as the rs fMRI, but I'm not sure if that's because it is listed as the first in the sources or if it is because it has the biggest matrix. Either way, this is causing problems downstream as the reference image for the task fMRI is not the same shape.

### What command did you use?

```shell
fprodents --notrack --skip-bids-validation -vv --participant_label surface -t visstim --use-syn --force-syn /data/coil_benchmark/data/bids/ /data/coil_benchmark/data/derivatives/fprodents/ participant
```

### What version of the software are you running?

0c497abbd9fa5b7a6f3f759d45ad7c94949b79be

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Work directory

**Comment by eilidhmacnicol** [comment]
Just seen that this has been discussed elsewhere (#255, #312) I did check before I posted but clearly I didn't go far enough back... 

Worth noting that no error was passed with respect to the reference workflow in my case, and it was just the downstream motion correction (using the reference image as the base) that flagged the problem.

**Comment by effigies** [comment]
Yes, we should deal with this. I see three options:

1) Split per-EPI (#312)
2) Group by shared parameters: (voxel sizes, TRT, echo time, PEDir)
3) Group by some shared parameters, use most common voxel size

Pushing me toward (1) is the fact that subjects might move within the scanner. If their head rotates around anything except the PE axis, then SyN will be working with out-of-plane blurs. If we're going to consider within-run head motion a problem to solve (#345), then we should not ignore it between-run.

In the future, we could consider methods to combine fieldmap estimates by shared parameters.

**Comment by eilidhmacnicol** [comment]
Although I was envisioning option 2 when I posted ( rotation between scans during anaesthetised scanning is pretty minimal and the biggest difference is usually a translation caused by field drift), I would also vote for option 1. 

In its current draft, `fprodents` is estimating the distortion for each BOLD file separately when using PE-POLAR field maps, so I like the continuity across methods.

**Comment by effigies** [comment]
Okay. I will rebase #312 on master, and we can aim to get it in for 2.5.0. Working on another bug at the moment, so might be tomorrow.

Not to shut down discussion, too quickly. Happy to consider other options, too.

**Comment by eilidhmacnicol** [comment]
Tomorrow is fine; fprodents has a lot of other problems that need addressing simultaneously 😅

**Comment by effigies** [comment]
#312 merged.
