### ISSUE TITLE
Poor SyN registration

### ISSUE THREAD

**Issue by effigies** [poldracklab/sdcflows#362]
### What happened?

ds004169/sub-0054 is an example of a subject where there is clear distortion induced by SDC. @pauljaffe can add some screenshots...

### What command did you use?

```shell
tacc-openneuro fmriprep command
```

### What version of the software are you running?

23.0.1

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by pauljaffe** [comment]
example from this subject: ![task-nback_run-1_contrast-2back-baseline_zstatmap](https://github.com/nipreps/sdcflows/assets/63369800/4c3ae6bf-ef95-493e-9df1-9f3a577f04cd)

**Comment by effigies** [comment]
This may be addressed by #421.
