### ISSUE TITLE
``scipy.signal.cubic`` is now deprecated

### ISSUE THREAD

**Issue by oesteban** [poldracklab/sdcflows#370]
### What happened?

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.cubic.html#scipy.signal.cubic

### What command did you use?

```shell
n/a
```

### What version of the software are you running?

n/a

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Well, at least BSpline has been around since 1.7 and they provide an exact equivalent. Last time we switched there was padding that increased runtime and had a weird edge case.

**Comment by oesteban** [comment]
Another big plus to port to BSpline is that it also evaluates the derivative, which is necessary for calculating the jacobian (the next big thing)

**Comment by oesteban** [comment]
> Well, at least BSpline has been around since 1.7 and they provide an exact equivalent. Last time we switched there was padding that increased runtime and had a weird edge case.

I've submitted a new PR. Indeed the padding is there, so it'd be great to try to recap what was the weird edge case and check again if the increased runtime will be problematic.
