### ISSUE TITLE
Wrangler: discard `part-phase` from `_epi`

### ISSUE THREAD

**Issue by oesteban** [poldracklab/sdcflows#384]
### What happened?

I believe the wrangler currently assumes all `_epi` files are to be used. Filtering out `part-phase` would be necessary.

### What command did you use?

```shell
n/a
```

### What version of the software are you running?

n/a

### How are you running this software?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by tsalo** [comment]
@oesteban I think you fixed this with #407.
