### ISSUE TITLE
BIDS URIs failing for at least some datasets

### ISSUE THREAD

**Issue by effigies** [poldracklab/sdcflows#456]
### What happened?

Phasediff fieldmaps are not being found when `IntendedFor: ['bids::...', ...]`.

cc @julietteboscheron

### What command did you use?

```shell
fmriprep-docker $DATA $OUT participant
```

### What version of the software are you running?

24.1.0rc0

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by Eva-St** [comment]
I had the same issue. I also used docker and fMRIPrep 24.1.0rc0 and my dataset is BIDS valid. fMRIPrep also did not report any error, it was only evident through the output.
